-- 코드를 입력하세요
WITH CTE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT I.FOOD_TYPE, REST_ID, REST_NAME, I.FAVORITES
FROM REST_INFO I 
JOIN CTE C ON I.FOOD_TYPE = C.FOOD_TYPE AND C.FAVORITES = I.FAVORITES
ORDER BY I.FOOD_TYPE DESC;
