SELECT INFO.FLAVOR FROM ICECREAM_INFO AS INFO INNER JOIN FIRST_HALF AS HALF ON INFO.FLAVOR = HALF.FLAVOR
WHERE HALF.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based' 
GROUP BY INFO.FLAVOR
ORDER BY HALF.TOTAL_ORDER DESC