-- 코드를 입력하세요
SELECT CR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH ON CR.CAR_ID = CH.CAR_ID
WHERE MONTH(START_DATE) = '10' AND CR.CAR_TYPE = '세단'
GROUP BY CR.CAR_ID
ORDER BY CR.CAR_ID DESC;