-- 코드를 입력하세요
SELECT DISTINCT CR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CR.CAR_ID = CH.CAR_ID
WHERE CH.START_DATE BETWEEN '2022-10-01' AND '2022-10-31' AND CR.CAR_TYPE = '세단'
ORDER BY CR.CAR_ID DESC;
