WITH RankedFish AS (
    SELECT 
        I.ID,
        I.FISH_TYPE,
        I.LENGTH,
        N.FISH_NAME,
        RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS RANKING
    FROM FISH_INFO  I
    JOIN FISH_NAME_INFO  N ON I.FISH_TYPE = N.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM RankedFish
WHERE RANKING = 1
ORDER BY ID;
