SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY = '과자' AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = '과자')
UNION ALL
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY = '국' AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = '국')
UNION ALL
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY = '김치' AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = '김치')
UNION ALL
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY = '식용유' AND PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = '식용유')
ORDER BY MAX_PRICE DESC;
